# PostgreSQL
development:
  adapter:  postgresql
  database: pilfer_server_development
  username: postgres

# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter:  postgresql
  database: pilfer_server_test
  username: postgres
